apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-image-prefetch
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - apps
  resources:
  - daemonsets
  resourceNames:
  - kube-image-prefetch
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-image-prefetch
subjects:
- kind: ServiceAccount
  name: kube-image-prefetch
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kube-image-prefetch
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-image-prefetch
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-image-prefetch-manager
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-image-prefetch-manager
  template:
    metadata:
      labels:
        app: kube-image-prefetch-manager
    spec:
      serviceAccountName: kube-image-prefetch
      containers:
      - name: kube-image-prefetch
        image: averagemarcus/kube-image-prefetch:latest
        imagePullPolicy: Always
